---
title: "Distributional consequences of climate policy"
author: "Drew Andersen"
date: "5/9/2022"
output: html_document
---
```{r setup, include = FALSE, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(here)
library(tidyverse)
library(kableExtra)
```
## Introduction

```{r}
#Loading in the data and baselines

data <- read_csv(here("HW3_data.csv"))[,-1] #upload and drop first column

#agg demand to new table
data_agg <- data %>% 
  mutate(Agg_Q = Q_Low_Kwh + Q_High_Kwh)

data_piv <- pivot_longer(data_agg, !Price_Cents, names_to = "Income_Group", values_to = "Q_Kwh") #pivot table to create column for districts (populated by four districts)

#est constants
price_e = 10 #cents/kWh
scc = 5100 # cent price/metric_ton 1000 kg
emis_lb_per_kwh = .85 #lbs CO2/kWh
emis_kg_per_kwh = emis_lb_per_kwh * 0.45359237 #kgs CO2/kWh
```

```{r}
#linear regression for functions
low_lm <- lm(Price_Cents ~ Q_Low_Kwh, data = data_agg)
high_lm <- lm(Price_Cents ~ Q_High_Kwh, data = data_agg)
agg_lm <- lm(Price_Cents ~ Agg_Q, data = data_agg)

high_dem <- function(quantity){  
  demand_p = high_lm$coefficients[2]*quantity + high_lm$coefficients[1]
  return(demand_p)
}
low_dem <- function(quantity){  
  demand_p = low_lm$coefficients[2]*quantity + low_lm$coefficients[1]
}
agg_dem <- function(quantity){
  demand_p = agg_lm$coefficients[2]*quantity + agg_lm$coefficients[1]
  return(demand_p)
}

#linear regression for inverse functions 
low_lm_inv<- lm(Q_Low_Kwh ~ Price_Cents, data = data_agg)
high_lm_inv <- lm(Q_High_Kwh ~ Price_Cents, data = data_agg)
agg_lm_inv <- lm(Agg_Q ~ Price_Cents, data = data_agg)

high_dem_inv <- function(price){  
  demand_q = high_lm_inv$coefficients[2]*price + high_lm_inv$coefficients[1]
}
low_dem_inv <- function(price){  
  demand_q = low_lm_inv$coefficients[2]*price + low_lm_inv$coefficients[1]
}
agg_dem_inv <- function(price){  
  demand_q = agg_lm_inv$coefficients[2]*price + agg_lm_inv$coefficients[1]
}

#agg_demand_slope = 1/((1/high_lm$coefficients[2]) + (1/low_lm$coefficients[2]))
```

##Q1
```{r}
mec = emis_kg_per_kwh * scc * (1/1000) #mec per kWh electricity
```

##Q2
```{r}
quant_e <- agg_dem_inv(price_e)
supply_slope <- price_e/quant_e

sup <- function(quantity){
  price = supply_slope * quantity
}
sup_inv <- function(price){
  quantity = price/supply_slope
}
```

```{r}
ggplot(data = data_piv, aes(x = Q_Kwh, y = Price_Cents, color = Income_Group)) +
  geom_point() +
  geom_abline(intercept = 0, slope = supply_slope, color = "purple") + 
  geom_abline(intercept = high_lm$coefficients[1], slope = high_lm$coefficients[2], color = "green") +
  geom_abline(intercept = low_lm$coefficients[1], slope = low_lm$coefficients[2], color = "blue") +
  geom_abline(intercept = agg_lm$coefficients[1], slope = agg_lm$coefficients[2], color = "red") +
  theme_minimal() + 
  ylim(0,35)
```
```{r}
kink_x = (high_lm$coefficients[1]-agg_lm$coefficients[1])/(agg_lm$coefficients[2]-high_lm$coefficients[2])
kink_y = agg_dem(kink_x)

kink_triangle = integrate(high_dem, 0, kink_x)$value - integrate(agg_dem, 0, kink_x)$value

con_surplus = ((.5*quant_e*(agg_lm$coefficients[1] - price_e)) + kink_triangle)/100
prod_surplus = (.5*quant_e*price_e)/100
env_cost = (mec * quant_e)/100 #div by hundred for dollar value
```

##Q3
```{r}
high_ben = (.5 * high_dem_inv(price_e) * (high_lm$coefficients[1] - price_e)) / 100
low_ben = (.5 * low_dem_inv(price_e) * (low_lm$coefficients[1] - price_e)) / 100
```

##Q4
```{r}
new_q = (mec - agg_lm$coefficients[1])/(agg_lm$coefficients[2]-supply_slope)
new_p = agg_dem(new_q)

high_ben_tax = (.5 * high_dem_inv(new_p) * (high_lm$coefficients[1] - new_p)) / 100
low_ben_tax = (.5 * low_dem_inv(new_p) * (low_lm$coefficients[1] - new_p)) / 100

prod_surplus_tax = (.5*new_q*(new_p-mec))/100
env_cost_tax = (mec * new_q)/100
tax_rev = new_q * (mec)/100
```

##Q5
```{r}
#scc = 5100

high_ben_tax = (.5 * high_dem_inv(new_p) * (high_lm$coefficients[1] - new_p)) / 100
low_ben_tax = (.5 * low_dem_inv(new_p) * (low_lm$coefficients[1] - new_p)) / 100
```

```{r}
scc = 5100
mec = emis_kg_per_kwh * scc * (1/1000) #mec per kWh electricity

new_q = (mec - agg_lm$coefficients[1]) / (agg_lm$coefficients[2] - supply_slope)
new_p = agg_dem(new_q)

tax_rev = new_q * (mec)/100

high_perc = high_dem_inv(new_p)/new_q
low_perc = 1 - high_perc

high_tax_share = tax_rev * high_perc
low_tax_share = tax_rev * low_perc

high_ben_plus_tax = ((.5 * high_dem_inv(new_p) * (high_lm$coefficients[1] - new_p)) / 100) + high_tax_share
low_ben_plus_tax = ((.5 * low_dem_inv(new_p) * (low_lm$coefficients[1] - new_p)) / 100) + low_tax_share
prod_surplus_tax = (.5*new_q*(new_p-mec))/100
```

a) "High" Income Consumer Benefit = `r round(high_ben_plus_tax,0)`
b) "Low" Income Consumer Benefit = `r round(low_ben_plus_tax,0)`
c) Producer Benefit = `r round(prod_surplus_tax,0)`

```{r}
scc = 7500
mec = emis_kg_per_kwh * scc * (1/1000) #mec per kWh electricity

scc = 10000
mec = emis_kg_per_kwh * scc * (1/1000) #mec per kWh electricity

scc = 15000
mec = emis_kg_per_kwh * scc * (1/1000) #mec per kWh electricity

scc = 12500
mec = emis_kg_per_kwh * scc * (1/1000) #mec per kWh electricity

#Need to copy and paste the code to each - make sure code is solid first
```

